#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
# Flag to set _is_active flag for ocphost or zosendpoint for all inventories
# Setting this value here tkes precendent of values set for all or group variables set in inventory file
# Can be overidden for a specific host in the inventory
# _is_active: false
