- name: "Retrieve route: '{{ route.name }}' from '{{ project_namespace.name }}\
    ' on '{{ ocp_cluster.hostname }}'"
  kubernetes.core.k8s_info:
    api_key: "{{ ocp_cluster.auth_token }}"
    kind: Route
    namespace: "{{ project_namespace.name }}"
    name: "{{ route.name }}"
    api_version: "{{ route.apiVersion }}"
  register: route_info

- name: "Verify route: '{{ route.name }}'"
  ansible.builtin.assert:
    that:
      - route_info.resources[0].status.ingress[0].conditions[0].type == "Admitted"
      - route_info.resources[0].status.ingress[0].conditions[0].status == "True"
  when: info_only is undefined
