#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

- name: Delete clusterServiceVersion with YAML file
  when: seaa_automation_strategy == "generate_deploy_yaml" or seaa_automation_strategy == "generate_yaml" or seaa_automation_strategy == "deploy_yaml"
  block:

    - name: Include task to generate yaml file
      when:
        - seaa_automation_strategy != "deploy_yaml"
      ansible.builtin.include_tasks: "{{ seaa_ansible_directory }}/tasks/generate_yaml.yml"
      vars:
        src: "{{ seaa_ansible_directory }}/yamls/zoscb/cluster-service-version.yaml"
        destination_file: "cluster-service-version.yaml"
        is_ocp_resource: true

    - name: "Delete brokerSubscription with Native YAML API: '{{ project_namespace.name }}' on '{{ ocp_cluster.hostname }}'"
      when: seaa_automation_strategy != "generate_yaml"
      kubernetes.core.k8s:
        state: absent
        namespace: "{{ project_namespace.name }}"
        definition: "{{ lookup('template', seaa_ansible_directory~'/yamls/zoscb/cluster-service-version.yaml') | from_yaml }}"
        wait: "{{ seaa_undeploy_wait | bool }}" # yes
        wait_timeout: "{{ seaa_undeploy_wait_timeout | int }}" # 600
        continue_on_error: "{{ seaa_undeploy_continue_on_error | bool }}"

    - name: Check for deletion of Broker Subscription
      ansible.builtin.pause:
        prompt: "Delete YAML for ClusterServiceVersion resource, press enter to continue ...:"
      when:
        - seaa_automation.prompt_during_automation | bool
        - seaa_automation.track_resources | bool
