#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
# ************************************
# z Opentools variable defaults 
# *************************************
zopentool_name: # blank tool value so validation loads file