#jinja2: lstrip_blocks: True
#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
kind: Secret
apiVersion: v1
metadata:
  name: signature-{{ oc_product.short_name }}-{{ oc_product.oc_version }}
data:
{% if oc_product.signatureUploadMode == 'file' %}
  publicKey: >-
    {{ lookup('ansible.builtin.file', oc_product.publicKey) | b64encode }}
  signatureData: >-
    {{ lookup('ansible.builtin.file', seaa_ansible_directory~'/roles/openshift_cluster/secrets/'~operator_name~oc_product.signatureFileExt) | b64encode }}
{% else %}
  publicKey: >-
    {{ lookup('ansible.builtin.url', oc_signature_uri~'/v'~oc_product.oc_version~'/'~oc_product.publicKey, split_lines=false) | b64encode }}
  signatureData: >-
    {{ lookup('ansible.builtin.url', oc_signature_uri~'/v'~oc_product.oc_version~'/'~operator_name~oc_product.signatureFileExt, split_lines=false) | b64encode }}
{% endif %}
type: Opaque

