#jinja2: lstrip_blocks: True
#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ seaa_sshkey_secrets_prefix }}{{ endpoint.username }}-{{ endpoint.name }}"
data:
  ssh_key: "{{ lookup('file', endpoint.SSHKeyFile, rstrip=False) | b64encode }}"
  username: "{{ endpoint.username | b64encode }}"
{% if endpoint.SSHKeyPassPhrase is defined and endpoint.SSHKeyPassPhrase is not none %}
  passphrase: "{{ endpoint.SSHKeyPassPhrase | b64encode }}"
{% endif %}
type: Opaque
