#jinja2: lstrip_blocks: True
---
kind: Secret
apiVersion: v1
metadata:
  name: "ssh-key-{{ endpoint.username }}-{{ endpoint.name }}"
data:
  ssh_key: "{{ lookup('file', endpoint.SSHKeyFile, rstrip=False) | b64encode }}"
  username: "{{ endpoint.username | b64encode }}"
{% if endpoint.SSHKeyPassPhrase is defined and endpoint.SSHKeyPassPhrase is not none %}
  passphrase: "{{ endpoint.SSHKeyPassPhrase | b64encode }}"
{% endif %}
type: Opaque
