#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
# Include ansible variables for product sub-operator being verifyed
- name: Include Go vars
  ansible.builtin.include_vars:
    file: "{{ zoscb_e2e_roles_directory }}/go/vars/main.yml"
  when: not go_vars_loaded

- name: Set go_vars_loaded flag
  ansible.builtin.set_fact:
    go_vars_loaded: true
  when: not go_vars_loaded

# Include sub operator role
- name: "Include role: 'go'"
  ansible.builtin.include_role:
    name: "go"

- name: Verify Operator Collection and SubOperator
  when:
    - not zpm_consolidated_operator | bool
  block:
    # VERIFY IMPORTED OPERATOR COLLECTION
    - name: Verify operatorCollection
      ansible.builtin.include_tasks: "{{ zoscb_e2e_roles_directory }}/common/tasks/operator_collection/verify/operatorCollection.yml"

    # VERIFY SUB-OPERATOR CONFIG
    - name: Verify subOperatorConfig
      ansible.builtin.include_tasks: "{{ zoscb_e2e_roles_directory }}/common/tasks/operator_collection/verify/subOperatorConfig.yml"

# Verify GO SUB-OPERATOR CUSTOM RESOURCES
- name: Verify goInstance on each zosendpoint
  ansible.builtin.include_tasks: "{{ go_cr_task_dir }}/verify/goInstance.yml"
  when:
    - hostvars[current_zosendpoint]._is_active
    - seaa_deploy_software_instances | bool
  with_items:
    - "{{ groups['zosendpoints'] }}"
  loop_control:
    loop_var: current_zosendpoint

- name: Verify validateGo on each zosendpoint
  ansible.builtin.include_tasks: "{{ go_cr_task_dir }}/verify/validateGo.yml"
  when:
    - hostvars[current_zosendpoint]._is_active
    - seaa_deploy_validate_crs | bool
    - sub_operator_go_create_validate_cr | bool
  with_items:
    - "{{ groups['zosendpoints'] }}"
  loop_control:
    loop_var: current_zosendpoint
