#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
# Include ansible variables for product sub-operator being verifyed
- name: Include Oelcpp vars
  ansible.builtin.include_vars:
    file: "{{ zoscb_e2e_roles_directory }}/oelcpp/vars/main.yml"
  when: not oelcpp_vars_loaded

- name: Set oelcpp_vars_loaded flag
  ansible.builtin.set_fact:
    oelcpp_vars_loaded: true
  when: not oelcpp_vars_loaded

# Include sub operator role
- name: "Include role: 'oelcpp'"
  ansible.builtin.include_role:
    name: "oelcpp"


- name: Verify Operator Collection and SubOperator
  when:
    - not zpm_consolidated_operator | bool
  block:

    # VERIFY IMPORTED OPERATOR COLLECTION
    - name: Verify operatorCollection
      ansible.builtin.include_tasks: "{{ zoscb_e2e_roles_directory }}/common/tasks/operator_collection/verify/operatorCollection.yml"

    # VERIFY SUB-OPERATOR CONFIG
    - name: Verify subOperatorConfig
      ansible.builtin.include_tasks: "{{ zoscb_e2e_roles_directory }}/common/tasks/operator_collection/verify/subOperatorConfig.yml"

# Verify OELCPP SUB-OPERATOR CUSTOM RESOURCES
- name: Verify oelcppInstance on each zosendpoint
  ansible.builtin.include_tasks: "{{ oelcpp_cr_task_dir }}/verify/oelcppInstance.yml"
  when:
    - hostvars[current_zosendpoint]._is_active
    - seaa_deploy_software_instances | bool
  with_items:
    - "{{ groups['zosendpoints'] }}"
  loop_control:
    loop_var: current_zosendpoint

- name: Verify validateOelcpp on each zosendpoint
  ansible.builtin.include_tasks: "{{ oelcpp_cr_task_dir }}/verify/validateOelcpp.yml"
  when:
    - hostvars[current_zosendpoint]._is_active
    - seaa_deploy_validate_crs | bool
    - sub_operator_oelcpp_create_validate_cr | bool
  with_items:
    - "{{ groups['zosendpoints'] }}"
  loop_control:
    loop_var: current_zosendpoint
