#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
# ****************************************************************************************************************************
# *
# - Include task to initialize the SEAA framwwork
# *
# ****************************************************************************************************************************
- name: Initiallize SEAA framework
  ansible.builtin.include_tasks: "util/seaa_initialize.yml"

- name: Deploy IBM Z and Cloud Modernization Stack components
  block:
    # ****************************************************************************************************************************
    # *
    # - name: Deploy ZOSCB on OCP CLUSTER
    # *
    # ****************************************************************************************************************************
    - name: Include Smart Deploy z/OS Cloud Broker task
      ansible.builtin.include_tasks: "util/smart_deploy_broker.yml"
      when:
        - seaa_deploy_objective != 'zpm'
        - seaa_deploy_role == "admin"
        - (seaa_zoscb_smart_deploy | bool and not zoscb_deployed) # and seaa_automation_strategy != "generate_yaml" # or seaa_deploy_objective == 'zoscb'
      tags:
        - always

    # Block to deploy Cloud Broker
    - name: Create Instance of ZOSCB
      when:
        - seaa_deploy_objective == 'zoscb' or seaa_deploy_role == "developer" # Used to deploy developer project creds
        - not zoscb_deployed
        - "'oel-dev' in  ansible_run_tags or 'zoscb' in ansible_run_tags or 'developer' in ansible_run_tags"
      tags:
        - oel-dev
        - zoscb
        - developer
      block:

        # Deploy Broker
        - name: Deploy Broker
          ansible.builtin.include_tasks: "deploy/zoscb.yml"

        # Set flag for ZOSCB being deployed to namespace
        - name: Set flag for ZOSCB being deployed to namespace
          ansible.builtin.set_fact:
            zoscb_deployed: true

    # ****************************************************************************************************************************
    # *
    # - name: Deploy ZPM on z/OS Endpoint
    # *
    # ****************************************************************************************************************************
    - name: Include Smart Deploy ZPM
      ansible.builtin.include_tasks: "util/smart_deploy_zpm.yml"
      when:
        - seaa_deploy_objective == 'zoscb' or seaa_deploy_objective == 'zpm'
        - (seaa_zoscb_smart_deploy | bool and seaa_zpm_smart_deploy | bool)
        - not zpm_deployed
      tags:
        - always

    # Block for installing sub-operator product
    - name: Create Instance of ZPM
      when:
        - seaa_deploy_objective == 'zpm'
        # - seaa_deploy_role == "admin"
        # - (not seaa_zoscb_smart_deploy | bool ) # or seaa_automation_strategy == "generate_yaml"
        - "'oel-dev' in  ansible_run_tags or 'zpm' in ansible_run_tags"
        - not zpm_deployed
      tags:
        - oel-dev
        - zpm
      block:

        # Deploy ZPM
        - name: Deploy ZPM
          ansible.builtin.include_tasks: "deploy/zpm.yml"

        # Set flag for ZPM being deployed to namespace
        - name: Set flag for ZPM being deployed to namespace
          ansible.builtin.set_fact:
            zpm_deployed: true

    # ****************************************************************************************************************************
    # *
    # - name: Deploy Go on z/OS Endpoint
    # *
    # ****************************************************************************************************************************
    # Block for installing sub-operator product
    - name: Create Instance of Go
      when: seaa_deploy_objective == 'go'
      tags:
        - oel-dev
        - go
      block:
        # Deploy Go
        - name: Deploy Go
          ansible.builtin.include_tasks: "deploy/go.yml"

    # ****************************************************************************************************************************
    # *
    # - name: Deploy Java on z/OS Endpoint
    # *
    # ****************************************************************************************************************************
    # Block for installing sub-operator product
    - name: Create Instance of Java
      when: seaa_deploy_objective == 'java'
      tags:
        - oel-dev
        - java
      block:
        # Deploy Java
        - name: Deploy Java
          ansible.builtin.include_tasks: "deploy/java.yml"

    # ****************************************************************************************************************************
    # *
    # - name: Deploy Nodejs on z/OS Endpoint
    # *
    # ****************************************************************************************************************************
    # Block for installing sub-operator product
    - name: Create Instance of Nodejs
      when: seaa_deploy_objective == 'nodejs'
      tags:
        - oel-dev
        - nodejs
      block:
        # Deploy NodeJS
        - name: Deploy NodeJS
          ansible.builtin.include_tasks: "deploy/nodejs.yml"

    # ****************************************************************************************************************************
    # *
    # - name: Deploy OelCpp on z/OS Endpoint
    # *
    # ****************************************************************************************************************************
    # Block for installing sub-operator product
    - name: Create Instance of Oelcpp
      when: seaa_deploy_objective == 'oelcpp'
      tags:
        - oel-dev
        - oelcpp
      block:
        # Deploy OelCPP
        - name: Deploy OelCPP
          ansible.builtin.include_tasks: "deploy/oelcpp.yml"


    # ****************************************************************************************************************************
    # *
    # - name: Deploy Python on z/OS Endpoint
    # *
    # ****************************************************************************************************************************
    # Block for installing sub-operator product
    - name: Create Instance of Python
      when: seaa_deploy_objective == 'python'
      tags:
        - oel-dev
        - python
      block:
        # Deploy Python
        - name: Deploy Python
          ansible.builtin.include_tasks: "deploy/python.yml"

    # ****************************************************************************************************************************
    # *
    # - name: Deploy ZOAU on z/OS Endpoint
    # *
    # ****************************************************************************************************************************
    # Block for installing sub-operator product
    - name: Create Instance of ZOAU
      when: seaa_deploy_objective == 'zoau'
      tags:
        - oel-dev
        - zoau
      block:
        # Deploy z/OS Open Automation Utility
        - name: Deploy z/OS Open Automation Utility
          ansible.builtin.include_tasks: "deploy/zoau.yml"

  always:
    - name: Unset this_project_name after iteration
      ansible.builtin.set_fact:
        this_project_name: none
