---
- name: "Destroy: Delete cloud broker subscription"
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars/main.yml
    - ../../vars/endpoints.yml

  tasks:
    - name: "Include role: 'ocp_cluster'"
      ansible.builtin.include_role:
        name: "ocp_cluster"

    - import_tasks: ../../tasks/destroy/brokerSubscription.yml
    - import_tasks: ../../tasks/destroy/clusterServiceVersion.yml
