#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: delegated
  options:
    managed: True
    ansible_connection_options: {}
lint: |
  set -e
  ansible-lint
platforms:
- name: Ubuntu
  groups:
  - k8s
provisioner:
  name: ansible
  env:
    OCP_CLUSTER_HOSTNAME: ${OCP_CLUSTER_HOSTNAME:-"<host_name>"}
    OCP_CLUSTER_PORT: ${OCP_CLUSTER_PORT:-6443}
    OCP_CLUSTER_AUTH_TOKEN: ${OCP_CLUSTER_AUTH_TOKEN:-"default-notoken"}

    ZPM_REGISTRY_HOSTNAME: ${ZPM_REGISTRY_HOSTNAME:-"<registry_host_name>"}
    ZPM_REGISTRY_USERNAME: ${ZPM_REGISTRY_USERNAME:-"default-nouser"}
    ZPM_REGISTRY_API_TOKEN: ${ZPM_REGISTRY_API_TOKEN:-"default-notoken"}

    NAMESPACE_NAME: ${NAMESPACE_NAME:-"default-zoscb-e2e"}
    NAMESPACE_API_VERSION: ${NAMESPACE_API_VERSION:-"project.openshift.io/v1"}

    PYTHON_INSTANCE_NAME: ${PYTHON_INSTANCE_NAME:-"example-python"}
    PYTHON_INSTANCE_KIND: ${PYTHON_INSTANCE_KIND:-"PythonInstance"}
    PYTHON_INSTANCE_API_VERSION: ${PYTHON_INSTANCE_API_VERSION:-"zos-python.zpm.zoscb.ibm.com/v0minor1patch9"}
    PYTHON_INSTANCE_FINALIZER: ${PYTHON_INSTANCE_FINALIZER:-"zos-python.zpm.zoscb.ibm.com/finalizer"}
    PYTHON_INSTANCE_LICENSE_ACCEPT: ${PYTHON_INSTANCE_LICENSE_ACCEPT:-true}
    PYTHON_INSTANCE_PRODUCT_VERSION: ${PYTHON_INSTANCE_PRODUCT_VERSION:-"3.10.0.0"}
verifier:
  name: ansible
scenario:
  name: cr_python_instance
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
