---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: delegated
  options:
    managed: True
    ansible_connection_options: {}
lint: |
  set -e
  ansible-lint
platforms:
- name: Ubuntu
  groups:
  - k8s
provisioner:
  name: ansible
  env:
    OCP_CLUSTER_HOSTNAME: ${OCP_CLUSTER_HOSTNAME:-"<host_name>"}
    OCP_CLUSTER_PORT: ${OCP_CLUSTER_PORT:-6443}
    OCP_CLUSTER_AUTH_TOKEN: ${OCP_CLUSTER_AUTH_TOKEN:-"default-notoken"}

    ZPM_REGISTRY_HOSTNAME: ${ZPM_REGISTRY_HOSTNAME:-"<registry_host_name>"}
    ZPM_REGISTRY_USERNAME: ${ZPM_REGISTRY_USERNAME:-"default-nouser"}
    ZPM_REGISTRY_API_TOKEN: ${ZPM_REGISTRY_API_TOKEN:-"default-notoken"}

    NAMESPACE_NAME: ${NAMESPACE_NAME:-"default-zoscb-e2e"}
    NAMESPACE_API_VERSION: ${NAMESPACE_API_VERSION:-"project.openshift.io/v1"}

    ZOAU_INSTANCE_NAME: ${ZOAU_INSTANCE_NAME:-"example-zoau"}
    ZOAU_INSTANCE_KIND: ${ZOAU_INSTANCE_KIND:-"ZOAUInstance"}
    ZOAU_INSTANCE_API_VERSION: ${ZOAU_INSTANCE_API_VERSION:-"zos-zoau.zpm.zoscb.ibm.com/v0minor1patch9"}
    ZOAU_INSTANCE_FINALIZER: ${ZOAU_INSTANCE_FINALIZER:-"zos-zoau.zpm.zoscb.ibm.com/finalizer"}
    ZOAU_INSTANCE_LICENSE_ACCEPT: ${ZOAU_INSTANCE_LICENSE_ACCEPT:-true}
    ZOAU_INSTANCE_PRODUCT_VERSION: ${ZOAU_INSTANCE_PRODUCT_VERSION:-"1.2.0.1"}
verifier:
  name: ansible
scenario:
  name: cr_zoau_instance
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
