#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: "Converge: Create suboperator config"
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars/main.yml
    - ../../../ocp_cluster/vars/main.yml
    - ../../../ocp_cluster/vars/endpoints.yml

  tasks:
    - name: "Include role: 'ocp_cluster'"
      ansible.builtin.include_role:
        name: "ocp_cluster"

    - name: "Include role: 'zpm'"
      ansible.builtin.include_role:
        name: "zpm"

    - import_tasks: ../../../../common/tasks/operator_collection/findFile.yml
    - import_tasks: ../../../../common/tasks/operator_collection/create/subOperatorConfig.yml
