---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    collections-path: "~/.ansible/collections/"
driver:
  name: delegated
  options:
    managed: True
    ansible_connection_options: {}
lint: |
  set -e
  ansible-lint
platforms:
- name: Ubuntu
  groups:
  - k8s
provisioner:
  name: ansible
  env:
    OCP_CLUSTER_HOSTNAME: ${OCP_CLUSTER_HOSTNAME:-"<host_name>"}
    OCP_CLUSTER_PORT: ${OCP_CLUSTER_PORT:-6443}
    OCP_CLUSTER_AUTH_TOKEN: ${OCP_CLUSTER_AUTH_TOKEN:-"default-notoken"}

    NAMESPACE_NAME: ${NAMESPACE_NAME:-"default-zoscb-e2e"}

    PVC_NAME: ${PVC_NAME:-"zoscloudbroker-pvc"}

    BROKER_INSTANCE_NAME: ${BROKER_INSTANCE_NAME:-"zoscloudbroker"}
    BROKER_INSTANCE_KIND: ${BROKER_INSTANCE_KIND:-"ZosCloudBroker"}
    BROKER_INSTANCE_API_VERSION: ${BROKER_INSTANCE_API_VERSION:-"zoscb.ibm.com/v2beta1"}
    BROKER_INSTANCE_LICENSE_ACCEPT: ${BROKER_INSTANCE_LICENSE_ACCEPT:-true}
    BROKER_INSTANCE_LOG_LEVEL: ${BROKER_INSTANCE_LOG_LEVEL:-"debug"}
    BROKER_INSTANCE_RESOURCES_CPU_LIMIT: ${BROKER_INSTANCE_RESOURCES_CPU_LIMIT:-"200m"}
    BROKER_INSTANCE_RESOURCES_MEMORY_LIMIT: ${BROKER_INSTANCE_RESOURCES_MEMORY_LIMIT:-"256Mi"}
    BROKER_INSTANCE_REQUESTS_CPU_LIMIT: ${BROKER_INSTANCE_REQUESTS_CPU_LIMIT:-"100m"}
    BROKER_INSTANCE_REQUESTS_MEMORY_LIMIT: ${BROKER_INSTANCE_REQUESTS_MEMORY_LIMIT:-"128Mi"}
    BROKER_INSTANCE_STORAGE_CONFIGURE: ${BROKER_INSTANCE_STORAGE_CONFIGURE:-true}
    BROKER_INSTANCE_STORAGE_ENABLED: ${BROKER_INSTANCE_STORAGE_ENABLED:-false}
    BROKER_INSTANCE_STORAGE_SIZE: ${BROKER_INSTANCE_STORAGE_SIZE:-"5Gi"}
    BROKER_INSTANCE_STORAGE_CLASS_NAME: ${BROKER_INSTANCE_STORAGE_CLASS_NAME:-""}
    BROKER_INSTANCE_STORAGE_VOLUME_MODE: ${BROKER_INSTANCE_STORAGE_VOLUME_MODE:-"Filesystem"}
verifier:
  name: ansible
scenario:
  name: broker_instance
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
