#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

- name: "Retrieve sub-operator CR {{ python_instance.kind }}: '{{ python_instance.name }}'"
  kubernetes.core.k8s_info:
    api_key: "{{ ocp_cluster.auth_token }}"
    kind: "{{ python_instance.kind }}"
    namespace: "{{ project_namespace.name }}"
    name: "{{ python_instance.name }}"
    api_version: "{{ python_instance.apiVersion }}"
  register: python_instance_info
  until: "python_instance_info.resources is defined and python_instance_info.resources[0].status.phase !='Running'"
  retries: "{{ seaa_verify_retries | int }}" # 30
  delay: "{{ seaa_verify_delay | int }}" # 10

- name: "Verify sub-operator CR {{ python_instance.kind }}: '{{ python_instance.name }}'"
  ansible.builtin.assert:
    that:
      - python_instance_info.resources[0].status.phase == "Succeeded"
  when: info_only is undefined
