#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: delegated
  options:
    managed: True
    ansible_connection_options: {}
lint: |
  set -e
  ansible-lint
platforms:
- name: Ubuntu
  groups:
  - k8s
provisioner:
  name: ansible
  env:
    OCP_CLUSTER_HOSTNAME: ${OCP_CLUSTER_HOSTNAME:-"<host_name>"}
    OCP_CLUSTER_PORT: ${OCP_CLUSTER_PORT:-6443}
    OCP_CLUSTER_AUTH_TOKEN: ${OCP_CLUSTER_AUTH_TOKEN:-"default-notoken"}

    NAMESPACE_NAME: ${NAMESPACE_NAME:-"default-zoscb-e2e"}

    ROUTE_NAME: ${ROUTE_NAME:-"e2e-automation-route"}

    OC_PRODUCT_NAME: ${OC_PRODUCT_NAME:-"zos-zoau"}
    OC_PRODUCT_API_VERSION: ${OC_PRODUCT_API_VERSION:-"zoscb.ibm.com/v2beta1"}
    OC_PRODUCT_FINALIZER: ${OC_PRODUCT_FINALIZER:-"operatorcollections.zoscb.ibm.com/finalizer"}

    SUBOP_CONFIG_API_VERSION: ${SUBOP_CONFIG_API_VERSION:-"zoscb.ibm.com/v2beta1"}
    SUBOP_CONFIG_FINALIZER: ${SUBOP_CONFIG_FINALIZER:-"suboperatorconfigs.zoscb.ibm.com/finalizer"}

    ZOAU_INSTANCE_NAME: ${ZOAU_INSTANCE_NAME:-"example-zoau"}
    ZOAU_INSTANCE_KIND: ${ZOAU_INSTANCE_KIND:-"ZOAUInstance"}
    ZOAU_INSTANCE_API_VERSION: ${ZOAU_INSTANCE_API_VERSION:-"zos-zoau.zpm.zoscb.ibm.com/v0minor1patch9"}
    ZOAU_INSTANCE_FINALIZER: ${ZOAU_INSTANCE_FINALIZER:-"zos-zoau.zpm.zoscb.ibm.com/finalizer"}
    ZOAU_INSTANCE_LICENSE_ACCEPT: ${ZOAU_INSTANCE_LICENSE_ACCEPT:-true}
    ZOAU_INSTANCE_PRODUCT_VERSION: ${ZOAU_INSTANCE_PRODUCT_VERSION:-"1.2.0.1"}

    VALIDATE_ZOAU_NAME: ${VALIDATE_ZOAU_NAME:-"example-validate-zoau"}
    VALIDATE_ZOAU_KIND: ${VALIDATE_ZOAU_KIND:-"ValidateZOAU"}
    VALIDATE_ZOAU_API_VERSION: ${VALIDATE_ZOAU_API_VERSION:-"zos-zoau.zpm.zoscb.ibm.com/v0minor1patch9"}
    VALIDATE_ZOAU_FINALIZER: ${VALIDATE_ZOAU_FINALIZER:-"zos-zoau.zpm.zoscb.ibm.com/finalizer"}
verifier:
  name: ansible
scenario:
  name: zoau
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
