---
- name: "Verify: Validate IBM Z and Cloud Modernization Stack - ZOAU Operator CRs"
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars/main.yml
    - ../../../ocp_cluster/vars/main.yml
    - ../../../ocp_cluster/vars/endpoints.yml

  tasks:
    - name: "Include role: 'ocp_cluster'"
      ansible.builtin.include_role:
        name: "ocp_cluster"

    - name: "Include role: 'zoau'"
      ansible.builtin.include_role:
        name: "zoau"

    # LOGIN TO THE OPENSHIFT CLUSTER
    - import_tasks: ../../../../common/tasks/clusterLogin.yml

    # FIND OPERATOR COLLECTION TAR.GZ FILE LOCALLY
    - import_tasks: ../../../../common/tasks/operator_collection/findFile.yml

    # VERIFY IMPORTED OPERATOR COLLECTION
    - import_tasks: ../../../../common/tasks/operator_collection/verify/operatorCollection.yml

    # VERIFY SUB-OPERATOR CONFIG
    - import_tasks: ../../../../common/tasks/operator_collection/verify/subOperatorConfig.yml

    # VERIFY NODEJS SUB-OPERATOR CUSTOM RESOURCES
    # - import_tasks: ../../tasks/custom_resource/verify/zoauInstance.yml
    - import_tasks: ../../tasks/custom_resource/verify/validateZoau.yml
