#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: "Converge: Create IBM Z and Cloud Modernization Stack - Java Operator CRs"
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars/main.yml
    - ../../../ocp_cluster/vars/main.yml
    - ../../../ocp_cluster/vars/endpoints.yml

  tasks:
    - name: "Include role: 'ocp_cluster'"
      ansible.builtin.include_role:
        name: "ocp_cluster"

    - name: "Include role: 'java'"
      ansible.builtin.include_role:
        name: "java"

    # LOGIN TO THE OPENSHIFT CLUSTER
    - import_tasks: ../../../../common/tasks/clusterLogin.yml

    # FIND OPERATOR COLLECTION TAR.GZ FILE LOCALLY
    - import_tasks: ../../../../common/tasks/operator_collection/findFile.yml

    # IMPORT OPERATOR COLLECTION
    - import_tasks: ../../../../common/tasks/operator_collection/create/operatorCollection.yml

    # CREATE SUB-OPERATOR CONFIG (MAP TO ENDPOINT)
    - import_tasks: ../../../../common/tasks/operator_collection/create/subOperatorConfig.yml

    # CREATE JAVA SUB-OPERATOR CUSTOM RESOURCES
    - import_tasks: ../../tasks/custom_resource/install/javaInstance.yml
    - import_tasks: ../../tasks/custom_resource/install/validateJava.yml
