---
- name: "Destroy: Delete IBM Z and Cloud Modernization Stack - Java Operator CRs"
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars/main.yml
    - ../../../ocp_cluster/vars/main.yml
    - ../../../ocp_cluster/vars/endpoints.yml

  tasks:
    - name: "Include role: 'ocp_cluster'"
      ansible.builtin.include_role:
        name: "ocp_cluster"

    - name: "Include role: 'java'"
      ansible.builtin.include_role:
        name: "java"

    # LOGIN TO THE OPENSHIFT CLUSTER
    - import_tasks: ../../../../common/tasks/clusterLogin.yml

    # DESTROY SUB-OPERATOR CUSTOM RESOURCES
    - import_tasks: ../../tasks/custom_resource/uninstall/validateJava.yml
    - import_tasks: ../../tasks/custom_resource/uninstall/javaInstance.yml

    # DELETE SUB-OPERATOR CONFIG
    - import_tasks: ../../../../common/tasks/operator_collection/destroy/subOperatorConfig.yml

    # DELETE IMPORTED OPERATOR COLLECTION
    - import_tasks: ../../../../common/tasks/operator_collection/destroy/operatorCollection.yml

    # CLEAN UP OPERATOR COLLECTION TAR.GZ FILE LOCALLY
    #- import_tasks: ../../../../common/tasks/operator_collection/deleteFile.yml
