#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

- name: Debug resource
  ansible.builtin.include_tasks: "{{ zoscb_e2e_roles_directory }}/common/tasks/debug_resource.yml"
  vars:
    resource_variable: "{{ endpoint }}"
  when: seaa_automation.debug | bool

- name: Create endpoint with YAML file
  when: seaa_automation_strategy == "generate_deploy_yaml" or seaa_automation_strategy == "generate_yaml" or seaa_automation_strategy == "deploy_yaml"
  block:

    - name: Set fact with encrypted endpoint variable
      when:
        - seaa_encrypt_sensitive_endpoint_vars | bool
        - zpm_registry.password is defined and zpm_registry.password | length > 0
      block:
        - name: Set path to sensitive file
          ansible.builtin.set_fact:
            encrypted_file: "{{ seaa_path_to_encrypted_files }}/{{ zpm_registry.password }}"

        - name: Set stats of file with sensitive data
          ansible.builtin.stat:
            path: "{{ encrypted_file }}"
          register: encrypted_file_stat
          no_log: "{{ seaa_security_secure_log | default(true) | bool }}"

        - name: Get encrypted content
          when: encrypted_file_stat.stat.exists
          ansible.builtin.slurp:
            src: "{{ encrypted_file }}"
          register: registry_password_content
          no_log: "{{ seaa_security_secure_log | default(true) | bool }}"

        - name: Set Encrypted registry password variable
          when:
            - encrypted_file_stat.stat.exists
            - not registry_password_content.failed
          ansible.builtin.set_fact:
            registry_password: "{{ registry_password_content.content | b64decode }}"
          no_log: "{{ seaa_security_secure_log | default(true) | bool }}"

        - name: Encrypted registry password file '{{ encrypted_file }}' not found
          when:
            - not encrypted_file_stat.stat.exists
          ansible.builtin.fail:
            msg: "Unable to find encrypted registry password file. Please verify it exist."

    - name: Set unencrypted registry password variable
      when:
        - not seaa_encrypt_sensitive_endpoint_vars | bool
        - zpm_registry.password is defined and zpm_registry.password | length > 0
      ansible.builtin.set_fact:
        registry_password: "{{ zpm_registry.password }}"
      no_log: "{{ seaa_security_secure_log | default(true) | bool }}"

    - name: Include task to generate yaml file for zos endpoint
      when:
        - seaa_automation_strategy != "deploy_yaml"
      ansible.builtin.include_tasks: "{{ seaa_ansible_directory }}/tasks/generate_yaml.yml"
      vars:
        src: "{{ seaa_ansible_directory }}/yamls/zoscb/zos-endpoint.yaml"
        destination_file: "{{ endpoint.name }}.yaml"
        is_zos_endpoint: true

    - name: "Create endpoint {{ endpoint.name }} with Native YAML API in '{{ project_namespace.name }}' on '{{ ocp_cluster.hostname }}'"
      when: seaa_automation_strategy != "generate_yaml"
      kubernetes.core.k8s:
        state: present
        namespace: "{{ project_namespace.name }}"
        definition: "{{ lookup('template', seaa_ansible_directory~'/yamls/zoscb/zos-endpoint.yaml') | from_yaml }}"

    - name: "Check for creation of z/OS Endpoint '{{ endpoint.name }}' in '{{ project_namespace.name }}' on '{{ ocp_cluster.hostname }}'"
      ansible.builtin.pause:
        prompt: "Create ZosEndpoint resource with Native YAML API,, press enter to continue ...:"
      when:
        - seaa_automation.prompt_during_automation | bool
        - seaa_automation.track_resources | bool
