#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

- ansible.builtin.include_tasks: "{{ zoscb_e2e_roles_directory }}/common/tasks/debug_resource.yml"
  vars:
    resource_variable: "{{ project_namespace }}"
    resource_variable_kind: Project
    resource_variable_name: "{{ project_namespace.name }}"
  when: seaa_automation.debug | bool

- name: Block to Deploy Project if it should be deployed
  when:
    - should_deploy_project is undefined or should_deploy_project
  block:
    - name: Reset authenticated user
      ansible.builtin.set_fact:
        authenticated_user: ""

    - name: Get authenticate user from cache
      ansible.builtin.set_fact:
        authenticated_user: "{{ ocp_cluster_cache | get_user_from_cache(current_ocphost) | trim }}"
      when:
        - ocp_cluster_cache is defined and ocp_cluster_cache != None
        - seaa_automation_strategy != "generate_yaml"

    - name: Create Project namespace with YAML file
      when: seaa_automation_strategy == "generate_deploy_yaml" or seaa_automation_strategy == "generate_yaml" or seaa_automation_strategy == "deploy_yaml"
      block:
        - name: Include task to generate yaml file
          when:
            - seaa_automation_strategy != "deploy_yaml"
          ansible.builtin.include_tasks: "{{ seaa_ansible_directory }}/tasks/generate_yaml.yml"
          vars:
            src: "{{ seaa_ansible_directory }}/yamls/ocp/project.yaml"
            destination_file: "project.yaml"
            is_ocp_resource: true

        - name: "Create Project with Native YAML API: '{{ project_namespace.name }}' on '{{ ocp_cluster.hostname }}'"
          when:
            - seaa_automation_strategy != "generate_yaml"
          block:

            - name: "Create Project with Native YAML API: '{{ project_namespace.name }}' on '{{ ocp_cluster.hostname }}'"
              kubernetes.core.k8s:
                state: present
                definition: "{{ lookup('template', seaa_ansible_directory~'/yamls/ocp/project.yaml') | from_yaml }}"
                wait: true

        - name: "Create Project for Multiple-Namespace projects on '{{ ocp_cluster.hostname }}'"
          when:
            - seaa_automation_strategy != "generate_yaml"
            - multi_namespaces | length > 0
            - broker_instance.multiNamespace is defined and broker_instance.multiNamespace | bool
            - not seaa_developer_deploys_project | bool
          block:

            - name: "Create Multi-Namespace Projects with Native YAML API: '{{ multi_namespaces }}' on '{{ ocp_cluster.hostname }}'"
              kubernetes.core.k8s:
                state: present
                definition: "{{ lookup('template', seaa_ansible_directory~'/yamls/ocp/m_project.yaml') | from_yaml }}"
                wait: true
              with_items:
                - "{{ multi_namespaces }}"
              loop_control:
                loop_var: m_namespace

        - name: "Check for creation of Project '{{ project_namespace.name }}' on '{{ ocp_cluster.hostname }}'"
          ansible.builtin.pause:
            prompt: "Create Project resource with Native YAML API, press enter to continue ...:"
          when:
            - seaa_automation.prompt_during_automation | bool
            - seaa_automation.track_resources | bool


