#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Include auth task
  when: hostvars[current_ocphost]._is_active
  ansible.builtin.include_role:
    name: openshift_cluster
    tasks_from: authenticate
  vars:
    openshift_host: "https://{{ hostvars[current_ocphost].ansible_host }}:{{ hostvars[current_ocphost].ansible_port }}"
    openshift_cluster_username: "{{ vault_username }}"
    openshift_cluster_password: "{{ vault_password }}"
    validate_certs: "{{ validate_openshift_certs }}"
    ca_cert: "{{ openshift_cert }}"

- name: Add new authenticated host
  when:
    - hostvars[current_ocphost]._is_active
    - vars[openshift_auth_results] is not none
    - openshift_auth_results.openshift_auth is defined
  block:

    # Debug new authentication status
    - name: Added new authenticated host '{{ current_ocphost }}' to cache
      ansible.builtin.debug:
        var: openshift_auth_results

    # Set auth token from newly authenticated results
    - name: Set auth token from newly authenticated results
      ansible.builtin.set_fact:
        openshift_auth_token: "{{ openshift_auth_results.openshift_auth.api_key }}"
      no_log: "{{ seaa_security_secure_log | default(true) | bool }}"

    # Set "zos_endpoints" fact for use in the role
    - name: Set "zos_endpoints" fact for use in the role
      ansible.builtin.include_tasks: "{{ seaa_ansible_directory }}/tasks/set_inventory_zosendpoints.yml"

    # Login to OCP cluster
    - name: Login to '{{ current_ocphost }}'-({{ hostvars[current_ocphost].ansible_host }})
      ansible.builtin.include_role:
        name: "common"
        tasks_from: "clusterLogin.yml"
