---
- name: Get CRS Token for current ocp host
  tags:
    - always
  when:
    - hostvars[current_ocphost]._is_active
  block:
    # #Include ocp_cluster ansible vars yaml files from E2E roles directory
    - name: Include variables OCP cluster
      ansible.builtin.include_vars:
        dir: "{{ zoscb_e2e_roles_directory | get_expanded_dir }}/ocp_cluster/vars"
        ignore_unknown_extensions: true
        extensions:
          - 'yml'
          - 'yaml'
      when: not ocp_cluster_vars_loaded

    - name: Set ocp_cluster_vars_loaded flag
      ansible.builtin.set_fact:
        ocp_cluster_vars_loaded: true
      when: not ocp_cluster_vars_loaded

    - name: Set Broker Instance Url
      ansible.builtin.set_fact:
        broker_application_url: "https://{{ route.name }}-{{ project_namespace.name }}.apps.{{ ocp_cluster.hostname | replace('api.', '') }}"

    - name: "Get CRSF token for '{{ broker_application_url }}'"
      ansible.builtin.uri:
        url: '{{ broker_application_url }}/api/csrf'
        return_content: true
        validate_certs: false
      register: csrf_output
      failed_when: "'Successfully generated CSRF token' not in csrf_output.content"
      no_log: "{{ seaa_security_secure_log | default(true) | bool }}"

    - name: Set OCP Host x_csrf_token
      ansible.builtin.set_fact:
        ocp_host_x_csrf_token: '{{ csrf_output.x_csrf_token }}'
        ocp_gorilla_csrf_cookie: '{{ csrf_output.cookies._gorilla_csrf }}'
      no_log: "{{ seaa_security_secure_log | default(true) | bool }}"
