#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
# HANDLE Cache initialize variables for smart deploy of ZOSCB and ZPM
- name: Smart deploy pre-run steps
  when:
    - seaa_zoscb_smart_deploy | bool
  tags:
    - always
  block:

    # # Set flags to check if ZOSCB and ZPM are deployed to namespace
    # - name: Reset flags to check if ZOSCB and ZPM are deployed to namespace
    #   ansible.builtin.set_fact:
    #     zoscb_deployed: false

    # Set flags to check if ZOSCB and ZPM are deployed to namespace
    - name: Reset flags to check if ZOSCB is deployed to namespace
      ansible.builtin.set_fact:
        zoscb_deployed: false

    - name: Reset flags to check if ZPM is deployed to namespace
      when: seaa_zpm_smart_deploy | bool
      ansible.builtin.set_fact:
        zpm_deployed: false

    # Check ocp_cluster_cache dictionary to see if Broker has been verified to be installed on current namespace
    - name: Check if zoscb is deploy in "{{ this_project_name }} on '{{ current_ocphost }}'"
      ansible.builtin.set_fact:
        check_is_zoscb_deployed: >-
          {{ ocp_cluster_cache
            | json_query(jmespath)
          }}
      when: ocp_cluster_cache is defined
      vars:
        jmespath: "{{ jmesq_zoscb_deployed }}"

    - name: Set zoscb_deployed fact from cache
      ansible.builtin.set_fact:
        zoscb_deployed: true
      when:
        - check_is_zoscb_deployed | type_debug != "NoneType"
        - check_is_zoscb_deployed is not none
        - check_is_zoscb_deployed | length > 0

    # Check ocp_cluster_cache dictionary to see if ZPM has been verified to be installed on current namespace
    - name: Check if zpm is deploy in "{{ this_project_name }} on '{{ current_ocphost }}'"
      ansible.builtin.set_fact:
        check_is_zpm_deployed: >-
          {{ ocp_cluster_cache
            | json_query(jmespath)
          }}
      when:
        - ocp_cluster_cache is defined
        - seaa_zpm_smart_deploy | bool
      vars:
        jmespath: "{{ jmesq_zpm_deployed }}"

    - name: Set zpm_deployed fact from cache
      ansible.builtin.set_fact:
        zpm_deployed: true
      when:
        - check_is_zpm_deployed is defined
        - check_is_zpm_deployed | type_debug != "NoneType"
        - check_is_zpm_deployed is not none
        - check_is_zpm_deployed | length > 0

    # Debug automation deployed status
    - name: Debug '{{ seaa_deploy_strategy }}' variables
      when: seaa_automation.debug | bool
      block:
        - name: Debug var ocp_cluster_cache
          ansible.builtin.debug:
            var: ocp_cluster_cache
          no_log: "{{ seaa_security_secure_log | default(true) | bool }}"

        - name: Debug var current_authenticated_host
          ansible.builtin.debug:
            var: current_authenticated_host

        - name: Debug var current_ocphost
          ansible.builtin.debug:
            var: current_ocphost

        - name: Debug var current_authenticated_host
          ansible.builtin.debug:
            var: this_project_name

        - name: Debug var zoscb_deployed
          ansible.builtin.debug:
            var: zoscb_deployed

        - name: Debug var zpm_deployed
          ansible.builtin.debug:
            var: zpm_deployed

        - name: Waiting for user response
          ansible.builtin.pause:
            prompt: PRE-Check '{{ seaa_deploy_strategy }}' - '{{ seaa_deploy_objective }}' in
              '{{ this_project_name }}' on '{{ current_ocphost }}', enter to continue...
          when: seaa_automation.prompt_during_automation | bool
