#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Initiallize SEAA framework
  ansible.builtin.include_tasks: "util/seaa_initialize.yml"

- name: Include Smart Deploy z/OS Cloud Broker task
  ansible.builtin.include_tasks: "util/smart_deploy_broker.yml"

- name: Manage SSHKey Secrets
  tags:
    - sshkey
  when:
    - hostvars[current_zosendpoint]._is_active
    - "'sshkey' in ansible_run_tags"
  ansible.builtin.include_role:
    name: openshift_cluster
    tasks_from: manage_secrets
  with_items:
    - "{{ groups['zosendpoints'] }}"
  loop_control:
    loop_var: current_zosendpoint

- name: Manage ZPM Registry Secrets
  tags:
    - registry
  when:
    - "'registry' in ansible_run_tags"
    - zpm_sets_registry_config is defined and zpm_sets_registry_config
    - zpm_registries is defined and zpm_registries | length > 0
    - hostvars[current_zosendpoint]._is_active
  ansible.builtin.include_role:
    name: openshift_cluster
    tasks_from: manage_secrets
  vars:
    secret_type: "registry"
    registry: "{{ zos_package_manager.registries }}"
  with_items:
    - "{{ groups['zosendpoints'] }}"
  loop_control:
    loop_var: current_zosendpoint
