#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
# ****************************************************************************************************************************
# *
# - Include task to set this_project_name from current_namespace for deployment
# *
# ****************************************************************************************************************************
- name: Set this_project_name
  ansible.builtin.include_tasks: "{{ seaa_ansible_directory }}/tasks/set_the_project_name.yml"
  tags: always

- name: Set JMES cache queries
  ansible.builtin.set_fact:
    jmesq_zoscb_deployed: "cached[? ocp_host=='{{ current_ocphost }}'] | [].zoscb_deployed_on | [?contains(@, '{{ this_project_name }}')][]"
    jmesq_zpm_deployed: "cached[? ocp_host=='{{ current_ocphost }}'] | [].zpm_deployed_on | [?contains(@, '{{ this_project_name }}')][]"
    jmesq_script_started: "cached[? ocp_host=='{{ current_ocphost }}'] | [].started_script_gen_on | [?contains(@, '{{ this_project_name }}')][]"
    jmesq_readme_started: "cached[? ocp_host=='{{ current_ocphost }}'] | [].started_readme_gen_on[].\"{{ this_project_name }}\""
  no_log: "{{ seaa_security_secure_log | default(true) | bool }}"


# ****************************************************************************************************************************
# *
# - Set "zos_endpoints" list for iterating multiple zos endpoint deployments
# *
# ****************************************************************************************************************************
- name: Set zos endpoint list
  ansible.builtin.include_tasks: "{{ seaa_ansible_directory }}/tasks/set_inventory_zosendpoints.yml"
  tags: always


# ****************************************************************************************************************************
# *
# - Set smart deploy flags and verify current zpm and zoswcb installation status
# *
# ****************************************************************************************************************************
- name: YAML generate and Smart Deploy Setup
  tags: always
  when:
    - seaa_zoscb_smart_deploy | bool or seaa_automation_strategy == "generate_yaml" or seaa_automation_strategy == "generate_deploy_yaml"
    - seaa_deploy_strategy != "verify"
  block:

    - name: Setup Smart Deploy and Generate
      ansible.builtin.include_tasks: "util/_init_generate.yml"

    - name: Setup Smart Deploy and Generate
      ansible.builtin.include_tasks: "util/_init_smartdeploy.yml"

  rescue:
    - name: Debug rescue error
      ansible.builtin.debug:
        msg: "Caught an error while setting up smart deploying on {{ current_ocphost }}"

# ****************************************************************************************************************************
# *
# - IMPORTANT: Include zos endpoint variable dictionaries used by each deployment to iterate over zosendpoints in inventory
# *
# ****************************************************************************************************************************
- name: Include endpoint variables
  when: not endpoint_vars_loaded
  ansible.builtin.include_vars: "{{ zoscb_e2e_roles_directory | get_expanded_dir }}/ocp_cluster/vars/endpoints.yml"
  tags: always

- name: Set endpoint_vars_loaded flag
  ansible.builtin.set_fact:
    endpoint_vars_loaded: true
  when: not endpoint_vars_loaded
