#jinja2: lstrip_blocks: True
#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
kind: "{{ validate_oelcpp.kind }}"
apiVersion: "{{ validate_oelcpp.apiVersion }}"
metadata:
  name: "{{ validate_oelcpp.name }}"
spec:
  product_cr_name: "{{ validate_oelcpp.productCRName }}"
  zosendpoint: "{{ validate_oelcpp.zosEndpoint }}"
  {% if oc_product.credential_type == "personal" %}
  credential: "ssh-key-{{ endpoint.username }}-{{ endpoint.name }}"
  {% endif %}
