#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: "Converge: Create OpenShift Cluster Resources"
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars/main.yml
    - ../../vars/endpoints.yml

  tasks:
    - name: "Include role: 'ocp_cluster'"
      ansible.builtin.include_role:
        name: "ocp_cluster"

    # LOGIN TO THE OPENSHIFT CLUSTER
    - import_tasks: ../../../../common/tasks/clusterLogin.yml

    # # CREATE NAMESPACE
    - import_tasks: ../../tasks/create/namespace.yml

    # # CREATE PERSISTENT VOLUME CLAIM
    - import_tasks: ../../tasks/create/persistentVolumeClaim.yml

    # CREATE OPERATOR GROUP
    - import_tasks: ../../tasks/create/operatorGroup.yml

    # CREATE Z CLOUD BROKER SUBSCRIPTION
    - import_tasks: ../../tasks/create/brokerSubscription.yml

    # CREATE Z CLOUD BROKER INSTANCE
    - import_tasks: ../../tasks/create/brokerInstance.yml

    # CREATE INSECURE ROUTE
    - import_tasks: ../../tasks/create/route.yml

    # CREATE ENDPOINT
    - import_tasks: ../../tasks/create/endpoint.yml
