#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: "Destroy: Delete OpenShift Cluster Resources"
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars/main.yml
    - ../../vars/endpoints.yml

  tasks:
    - name: "Include role: 'ocp_cluster'"
      ansible.builtin.include_role:
        name: "ocp_cluster"

    # LOGIN TO THE OPENSHIFT CLUSTER
    - import_tasks: ../../../../common/tasks/clusterLogin.yml

    # DELETE PRODUCTS AND ZPM
    - import_tasks: ../../tasks/destroy/deleteProducts.yml

    # DELETE THE CREATED ENDPOINT
    - import_tasks: ../../tasks/destroy/endpoint.yml

    # DELETE INSECURE ROUTE
    - import_tasks: ../../tasks/destroy/route.yml

    # DELETE Z CLOUD BROKER INSTANCE
    - import_tasks: ../../tasks/destroy/brokerInstance.yml

    # DELETE Z CLOUD BROKER SUBSCRIPTION
    - import_tasks: ../../tasks/destroy/brokerSubscription.yml

    # DELETE CLUSTER SERVICE VERSION (OPERATOR)
    - import_tasks: ../../tasks/destroy/clusterServiceVersion.yml

    # DELETE OPERATOR GROUP
    - import_tasks: ../../tasks/destroy/operatorGroup.yml

    # DELETE PERSISTENT VOLUME CLAIM
    - import_tasks: ../../tasks/destroy/persistentVolumeClaim.yml
