---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: delegated
  options:
    managed: True
    ansible_connection_options: {}
lint: |
  set -e
  ansible-lint
platforms:
- name: Ubuntu
  groups:
  - k8s
provisioner:
  name: ansible
  env:
    OCP_CLUSTER_HOSTNAME: ${OCP_CLUSTER_HOSTNAME:-"<host_name>"}
    OCP_CLUSTER_PORT: ${OCP_CLUSTER_PORT:-6443}
    OCP_CLUSTER_AUTH_TOKEN: ${OCP_CLUSTER_AUTH_TOKEN:-"default-notoken"}

    NAMESPACE_NAME: ${NAMESPACE_NAME:-"default-zoscb-e2e"}

    ROUTE_NAME: ${ROUTE_NAME:-"e2e-automation-route"}

    OC_PRODUCT_NAME: ${OC_PRODUCT_NAME:-"zos-python"}
    OC_PRODUCT_API_VERSION: ${OC_PRODUCT_API_VERSION:-"zoscb.ibm.com/v2beta1"}
    OC_PRODUCT_FINALIZER: ${OC_PRODUCT_FINALIZER:-"operatorcollections.zoscb.ibm.com/finalizer"}

    SUBOP_CONFIG_API_VERSION: ${SUBOP_CONFIG_API_VERSION:-"zoscb.ibm.com/v2beta1"}
    SUBOP_CONFIG_FINALIZER: ${SUBOP_CONFIG_FINALIZER:-"suboperatorconfigs.zoscb.ibm.com/finalizer"}

    PYTHON_INSTANCE_NAME: ${PYTHON_INSTANCE_NAME:-"example-python"}
    PYTHON_INSTANCE_KIND: ${PYTHON_INSTANCE_KIND:-"PythonInstance"}
    PYTHON_INSTANCE_API_VERSION: ${PYTHON_INSTANCE_API_VERSION:-"zos-python.zpm.zoscb.ibm.com/v0minor1patch9"}
    PYTHON_INSTANCE_FINALIZER: ${PYTHON_INSTANCE_FINALIZER:-"zos-python.zpm.zoscb.ibm.com/finalizer"}
    PYTHON_INSTANCE_LICENSE_ACCEPT: ${PYTHON_INSTANCE_LICENSE_ACCEPT:-true}
    PYTHON_INSTANCE_PRODUCT_VERSION: ${PYTHON_INSTANCE_PRODUCT_VERSION:-"3.10.0.0"}

    VALIDATE_PYTHON_NAME: ${VALIDATE_PYTHON_NAME:-"example-validate-python"}
    VALIDATE_PYTHON_KIND: ${VALIDATE_PYTHON_KIND:-"ValidatePython"}
    VALIDATE_PYTHON_API_VERSION: ${VALIDATE_PYTHON_API_VERSION:-"zos-python.zpm.zoscb.ibm.com/v0minor1patch9"}
    VALIDATE_PYTHON_FINALIZER: ${VALIDATE_PYTHON_FINALIZER:-"zos-python.zpm.zoscb.ibm.com/finalizer"}
verifier:
  name: ansible
scenario:
  name: python
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
