---
- name: "Destroy: Delete suboperator config"
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars/main.yml
    - ../../../ocp_cluster/vars/main.yml
    - ../../../ocp_cluster/vars/endpoints.yml

  tasks:
    - name: "Include role: 'ocp_cluster'"
      ansible.builtin.include_role:
        name: "ocp_cluster"

    - name: "Include role: 'zoau'"
      ansible.builtin.include_role:
        name: "zoau"

    - import_tasks: ../../../../common/tasks/operator_collection/destroy/subOperatorConfig.yml
