#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
# Variables file for ZPM Operator

# ZPM_REGISTRY CREDENTIALS  TODO:DOC -  Inventory > Ansible Var Defaults
zpm_registry:
  host: "{{ hostvars[current_ocphost].zpm_registry_host | default(lookup('vars', 'zpm_registry_host'), true) }}"
  username: "{{ hostvars[current_ocphost].zpm_registry_user | default(lookup('vars', 'zpm_registry_user'), true) }}"
  apiToken: "{{ hostvars[current_ocphost].zpm_registry_password | default(lookup('vars', 'zpm_registry_password'), true) }}"


# SUB-OPERATOR (Operator Collection) - TODO:DOC -  Inventory > Ansible Var Defaults, Constants
oc_product:
  short_name: "{{ hostvars[current_ocphost].zpm_product_short_name | default(lookup('vars', 'zpm_product_short_name'), true) }}"
  code_name: "{{ hostvars[current_ocphost].zpm_product_code_name | default(lookup('vars', 'zpm_product_code_name'), true) | default('', true) }}"
  name: "{{ hostvars[current_ocphost].zpm_product_name | default(lookup('vars', 'zpm_product_name'), true) }}"
  oc_version: "{{ hostvars[current_ocphost].zpm_oc_version | default(lookup('vars', 'zpm_oc_version'), true) }}"
  oci_version: "{{ hostvars[current_ocphost].zpm_oci_version | default(lookup('vars', 'zpm_oci_version'), true) }}"
  apiVersion: "{{ lookup('vars', 'oc_product_api_version') }}"
  finalizers:
    - "{{ lookup('vars', 'oc_product_finalizer') }}"
  import_mode: "{{ hostvars[current_ocphost].zpm_import_mode | default(lookup('vars', 'zpm_import_mode'), true) | default('galaxy', true) }}"
  import_url: "{{ hostvars[current_ocphost].zpm_import_url | default(lookup('vars', 'zpm_import_url'), true) | default('https://galaxy.ansible.com', true) }}"
  git_token: "{{ hostvars[current_ocphost].zpm_git_token | default(lookup('vars', 'zpm_git_token'), true) | default('', true) }}"
  delete_collections: "{{ hostvars[current_ocphost].oc_product_delete_collections |
    default(lookup('vars', 'oc_product_delete_collections', errors='ignore'), true) | default(true) }}"
  signatureFile: "{{ lookup('vars', 'zpm_signature_file') if lookup('vars', 'zpm_signature_upload_mode', default='url') == 'url' else
                      seaa_ansible_directory~'/roles/openshift_cluster/secrets/ibm-'~hostvars[current_ocphost].zpm_product_name |
                       default(lookup('vars', 'zpm_product_name'), true) | replace('-', '_')~'-'~hostvars[current_ocphost].zpm_oc_version |
                       default(lookup('vars', 'zpm_oc_version'), true)~'.sig'
                  }}"
  signatureFileExt: "{{ hostvars[current_ocphost].zpm_signature_file_ext | default(lookup('vars', 'zpm_signature_file_ext', default='.sig'), true) }}"
  signatureUploadMode: "{{ hostvars[current_ocphost].zpm_signature_upload_mode | default(lookup('vars', 'zpm_signature_upload_mode', default='url'), true) }}"
  publicKey: "{{ lookup('vars', 'zpm_public_key') if lookup('vars', 'zpm_signature_upload_mode', default='url') == 'url' else
                    seaa_ansible_directory~'/roles/openshift_cluster/secrets/'~lookup('vars', 'zpm_public_key')
              }}"
  skipVerify: "{{ hostvars[current_ocphost].zpm_skip_verify | default(lookup('vars', 'zpm_skip_verify'), true) }}"
  domain: "{{ lookup('vars', 'oc_product_domain') }}"
  credential_type: "{{ lookup('vars', 'zpm_credential_type', default='') }}"

# SUB-OPERATOR CONFIG TODO:DOC -  Ansible Var Defaults, Runtime
subop_config:
  apiVersion: "{{ lookup('vars', 'subop_config_api_version') }}"
  endpointNames: "{{ zos_endpoints }}"  # "{{ endpoint.name }}"
  finalizers:
    - "{{ lookup('vars', 'subop_config_finalizer') }}"

##### Edit variables below for any Custom Resources (CRs) #####

# ZPM Sub-Operator CRs
zos_package_manager:
  name: "{{ hostvars[current_ocphost].zpm_instance_name |
            default(zpm_instance_prefix | append_str_if_not_null('-'~current_zosendpoint), true)  |
            default(lookup('vars', 'zpm_instance_name'), true) }}"
  kind: "{{ lookup('vars', 'zpm_instance_kind') }}"
  apiVersion: "{{ lookup('vars', 'zpm_instance_api_version') }}"
  finalizers:
    - "{{ lookup('vars', 'zpm_instance_finalizer') }}"
  zosEndpoint: "{{ endpoint.name }}"
  installDirectoryPath: "{{ endpoint.zpm_installation_dir }}"
  stateDirectoryPath: "{{ endpoint.zpm_state_dir }}"
  javaHomeDirectory: "{{ hostvars[current_zosendpoint].zpm_java_home_directory |
   default(lookup('vars', 'zpm_java_home_directory'), true) }}" # "{{ lookup('vars', 'zpm_java_home_directory') }}"
  productsHLQ: "{{ endpoint.zpm_product_hlq }}" # "{{ lookup('vars', 'zpm_product_hlq') }}"
  zpmRegistryLocation: "{{ zpm_registry.host }}"
  zpmRegistryProxyHost: "{{ lookup('vars', 'zpm_registry_proxy_host') | default('', true) }}"
  zpmRegistryProxyPort: "{{ lookup('vars', 'zpm_registry_proxy_port') | default('', true) }}"
  licenseAccept: "{{ lookup('vars', 'zpm_instance_license_accept') | bool }}"

# TODO:DOC -  Inventory > Ansible Var Defaults, Constants
zos_package_manager_diagnostics:
  name: "{{ hostvars[current_ocphost].zpm_diagnostics_name |
            default(zpm_diagnostics_prefix | append_str_if_not_null('-'~current_zosendpoint), true)  |
            default(lookup('vars', 'zpm_diagnostics_name'), true) }}"
  kind: "{{ lookup('vars', 'zpm_diagnostics_kind') }}"
  apiVersion: "{{ lookup('vars', 'zpm_diagnostics_api_version') }}"
  finalizers:
    - "{{ lookup('vars', 'zpm_diagnostics_finalizer') }}"
  zosEndpoint: "{{ endpoint.name }}"
  productCRName: "{{ hostvars[current_ocphost].zpm_instance_name |
            default(zpm_instance_prefix | append_str_if_not_null('-'~current_zosendpoint), true)  |
            default(lookup('vars', 'zpm_instance_name'), true) }}"

product_filename: "{{ oc_product.oci_version if seaa_append_version_to_software_instances | bool == true else oc_product.oc_version }}"
