---
- name: Deploy SSH Key from Inventory as Secrets in OpenShift
  hosts: localhost
  gather_facts: false

  vars_files:
    # Reference ZSTACK ansible variable constants  (**** Requires "seaa_variables_directory" variable to be set for this playbook ****)
    - "{{ seaa_variables_directory }}/config/seaa_config.yaml"
    - "{{ seaa_variables_directory }}/config/seaa_trouble.yaml"
    - "{{ seaa_variables_directory }}/protected/constants.yaml"

  tasks:
    # ****************************************************************************************************************************
    # *
    # Load Default variables from default variable files
    # *
    # ****************************************************************************************************************************
    - name: Include Default Variables from files
      ansible.builtin.include_vars:
        dir: "{{ seaa_variables_directory }}/defaults"
        ignore_unknown_extensions: true
        extensions:
          - 'yaml'
      tags:
        - always

    # ****************************************************************************************************************************
    #
    # This custom module validates variables used in the seaa framework playbook run, this validation takes into count all 
    # variable files and inventory files used for playbook run. The following is sudo code for the ansibel-inventory 
    # command used with this module:
    #
    # ansible-inventory -i sample-inventory.yaml --list --yaml -e @<seaa_ansible_variables_dir>/config/seaa_config.yaml \
    #   -e @<seaa_ansible_variables_dir>/protected/constants.yaml \
    #   -e @<seaa_ansible_variables_dir>defaults/<all_default_files> \
    #   -e 'SEAA_EXTRA_VARS' environment variable
    #
    # By default the validation module uses the 'seaa_schema.yaml' file located as below:
    # <seaa_ansible_variables_dir>/protected/seaa_schema.yaml
    #
    # ******************************************************************ansibl**********************************************************
    - name: Validate SEAA framework inventory and ansible variables
      run_once: true
      seaa_variables_validation:
        inventory_source: "{{ ansible_inventory_sources }}"
      tags: always

    # Dynamically INCLUDE ansible role
    - name: Include z/OS Dev Env role to deploy SSH Key secrets
      ansible.builtin.include_role:
        name: "zos_dev_envs"
      when:
        - hostvars[current_ocphost]._is_active
      vars:
        seaa_deploy_objective: secrets
      with_items:
        - "{{ groups['ocphosts'] }}"
      loop_control:
        loop_var: current_ocphost
      tags:
        - sshkey
