---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: delegated
  options:
    managed: True
    ansible_connection_options: {}
lint: |
  set -e
  ansible-lint
platforms:
- name: Ubuntu
  groups:
  - k8s
provisioner:
  name: ansible
  env:
    OCP_CLUSTER_HOSTNAME: ${OCP_CLUSTER_HOSTNAME:-"<host_name>"}
    OCP_CLUSTER_PORT: ${OCP_CLUSTER_PORT:-6443}
    OCP_CLUSTER_AUTH_TOKEN: ${OCP_CLUSTER_AUTH_TOKEN:-"default-notoken"}

    NAMESPACE_NAME: ${NAMESPACE_NAME:-"default-zoscb-e2e"}

    ROUTE_NAME: ${ROUTE_NAME:-"e2e-automation-route"}

    OC_PRODUCT_NAME: ${OC_PRODUCT_NAME:-"zos-oelcpp"}
    OC_PRODUCT_API_VERSION: ${OC_PRODUCT_API_VERSION:-"zoscb.ibm.com/v2beta1"}
    OC_PRODUCT_FINALIZER: ${OC_PRODUCT_FINALIZER:-"operatorcollections.zoscb.ibm.com/finalizer"}

    SUBOP_CONFIG_API_VERSION: ${SUBOP_CONFIG_API_VERSION:-"zoscb.ibm.com/v2beta1"}
    SUBOP_CONFIG_FINALIZER: ${SUBOP_CONFIG_FINALIZER:-"suboperatorconfigs.zoscb.ibm.com/finalizer"}

    OELCPP_INSTANCE_NAME: ${OELCPP_INSTANCE_NAME:-"example-oelcpp"}
    OELCPP_INSTANCE_KIND: ${OELCPP_INSTANCE_KIND:-"OelCPPInstance"}
    OELCPP_INSTANCE_API_VERSION: ${OELCPP_INSTANCE_API_VERSION:-"zos-oelcpp.zpm.zoscb.ibm.com/v0minor1patch1"}
    OELCPP_INSTANCE_FINALIZER: ${OELCPP_INSTANCE_FINALIZER:-"zos-oelcpp.zpm.zoscb.ibm.com/finalizer"}
    OELCPP_INSTANCE_LICENSE_ACCEPT: ${OELCPP_INSTANCE_LICENSE_ACCEPT:-true}
    OELCPP_INSTANCE_PRODUCT_VERSION: ${OELCPP_INSTANCE_PRODUCT_VERSION:-"1.0.0.0"}

    VALIDATE_OELCPP_NAME: ${VALIDATE_OELCPP_NAME:-"example-validate-oelcpp"}
    VALIDATE_OELCPP_KIND: ${VALIDATE_OELCPP_KIND:-"ValidateOelCPP"}
    VALIDATE_OELCPP_API_VERSION: ${VALIDATE_OELCPP_API_VERSION:-"zos-oelcpp.zpm.zoscb.ibm.com/v0minor1patch1"}
    VALIDATE_OELCPP_FINALIZER: ${VALIDATE_OELCPP_FINALIZER:-"zos-oelcpp.zpm.zoscb.ibm.com/finalizer"}
verifier:
  name: ansible
scenario:
  name: oelcpp
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
