---
- name: "Converge: Create suboperator custom resource"
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars/main.yml
    - ../../../ocp_cluster/vars/main.yml
    - ../../../ocp_cluster/vars/endpoints.yml

  tasks:
    - name: "Include role: 'ocp_cluster'"
      ansible.builtin.include_role:
        name: "ocp_cluster"

    - name: "Include role: 'go'"
      ansible.builtin.include_role:
        name: "go"

    - import_tasks: ../../tasks/custom_resource/install/validateGo.yml
