#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: delegated
  options:
    managed: True
    ansible_connection_options: {}
lint: |
  set -e
  ansible-lint
platforms:
- name: Ubuntu
  groups:
  - k8s
provisioner:
  name: ansible
  env:
    OCP_CLUSTER_HOSTNAME: ${OCP_CLUSTER_HOSTNAME:-"<host_name>"}
    OCP_CLUSTER_PORT: ${OCP_CLUSTER_PORT:-6443}
    OCP_CLUSTER_AUTH_TOKEN: ${OCP_CLUSTER_AUTH_TOKEN:-"default-notoken"}

    NAMESPACE_NAME: ${NAMESPACE_NAME:-"default-zoscb-e2e"}

    ROUTE_NAME: ${ROUTE_NAME:-"e2e-automation-route"}

    OC_PRODUCT_NAME: ${OC_PRODUCT_NAME:-"zos-nodejs"}
    OC_PRODUCT_API_VERSION: ${OC_PRODUCT_API_VERSION:-"zoscb.ibm.com/v2beta1"}
    OC_PRODUCT_FINALIZER: ${OC_PRODUCT_FINALIZER:-"operatorcollections.zoscb.ibm.com/finalizer"}

    SUBOP_CONFIG_API_VERSION: ${SUBOP_CONFIG_API_VERSION:-"zoscb.ibm.com/v2beta1"}
    SUBOP_CONFIG_FINALIZER: ${SUBOP_CONFIG_FINALIZER:-"suboperatorconfigs.zoscb.ibm.com/finalizer"}

    NODEJS_INSTANCE_NAME: ${NODEJS_INSTANCE_NAME:-"example-nodejs"}
    NODEJS_INSTANCE_KIND: ${NODEJS_INSTANCE_KIND:-"NodejsInstance"}
    NODEJS_INSTANCE_API_VERSION: ${NODEJS_INSTANCE_API_VERSION:-"zos-nodejs.zpm.zoscb.ibm.com/v0minor1patch18"}
    NODEJS_INSTANCE_FINALIZER: ${NODEJS_INSTANCE_FINALIZER:-"zos-nodejs.zpm.zoscb.ibm.com/finalizer"}
    NODEJS_INSTANCE_LICENSE_ACCEPT: ${NODEJS_INSTANCE_LICENSE_ACCEPT:-true}
    NODEJS_INSTANCE_PRODUCT_VERSION: ${NODEJS_INSTANCE_PRODUCT_VERSION:-"16.0.0.1"}

    VALIDATE_NODEJS_NAME: ${VALIDATE_NODEJS_NAME:-"example-validate-nodejs"}
    VALIDATE_NODEJS_KIND: ${VALIDATE_NODEJS_KIND:-"ValidateNodejs"}
    VALIDATE_NODEJS_API_VERSION: ${VALIDATE_NODEJS_API_VERSION:-"zos-nodejs.zpm.zoscb.ibm.com/v0minor1patch18"}
    VALIDATE_NODEJS_FINALIZER: ${VALIDATE_NODEJS_FINALIZER:-"zos-nodejs.zpm.zoscb.ibm.com/finalizer"}
verifier:
  name: ansible
scenario:
  name: nodejs
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
