#jinja2: lstrip_blocks: True
#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
apiVersion: "{{ oc_product.apiVersion }}"
kind: OperatorCollection
metadata:
  name: "{{ oc_product.name }}.{{ oc_product.domain }}.{{ oc_product.oc_version }}"
{% if oc_product.import_mode == 'upload' %}
  labels:
    managed-by: "{{ broker_instance.managed }}"
    instance-name: "{{ broker_instance.name }}"
    operator-domain: "{{ oc_product.domain }}"
    operator-name: "{{ oc_product.name }}"
    operator-version: "{{ oc_product.oc_version }}"
{% endif %}
spec:
{% if oc_product.skipVerify == true %}
  {% if oc_product.import_mode != 'upload' %}
  collectionURL: "{{ oc_download_uri }}"
  {% endif %}
  skipSignatureVerification: true
{% else %}
  {% if zpm_consolidated_operator | bool == false and oc_product.import_mode != 'upload' %}
  collectionURL: "{{ oc_signature_uri~'/v'~oc_product.oc_version~'/'~operator_name~'.tar.gz' }}"
  {% elif oc_product.import_mode != 'upload' %}
  collectionURL: "{{ oc_download_uri }}"
  {% endif %}
  skipSignatureVerification: false
  signatureSecret: signature-{{ oc_product.short_name }}-{{ oc_product.oc_version }}
{% endif %}
