#jinja2: lstrip_blocks: True
#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
apiVersion: "{{ oc_product.apiVersion }}"
kind: OperatorCollection
metadata:
  name: "{{ oc_product.name }}.{{ oc_product.domain }}.{{ oc_product.oc_version }}"
spec:
{% if oc_product.skipVerify == true %}
  collectionURL: "{{ oc_download_uri }}"
  skipSignatureVerification: true
{% else %}
  {% if zpm_consolidated_operator | bool == false %}
  collectionURL: "{{ oc_signature_uri~'/v'~oc_product.oc_version~'/'~operator_name~'.tar.gz' }}"
  {% else %}
  collectionURL: "{{ oc_download_uri }}"
  {% endif %}
  skipSignatureVerification: false
  signatureSecret: signature-{{ oc_product.short_name }}-{{ oc_product.oc_version }}
{% endif %}

