#jinja2: lstrip_blocks: True
#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
kind: OperatorGroup
apiVersion: "{{ operator_group.apiVersion }}"
metadata:
  name: "{{ operator_group.name }}"
spec:
  targetNamespaces:
    - "{{ project_namespace.name }}"
