#jinja2: lstrip_blocks: True
#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
kind: PersistentVolumeClaim
apiVersion: "{{ persistent_volume_claim.apiVersion }}"
metadata:
  name: "{{ persistent_volume_claim.name }}"
spec:
  accessModes:
  {% for accessMode in persistent_volume_claim.accessModes %}
    - "{{ accessMode }}"
  {% endfor %}
  resources:
    requests:
      storage: "{{ persistent_volume_claim.storage }}"
  volumeMode: "{{ persistent_volume_claim.volumeMode }}"
  storageClassName: "{{ persistent_volume_claim.storageClassName }}"
