#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

- name: "Find operator collection tar.gz file locally"
  ansible.builtin.stat:
    path: "{{ zoscb_e2e_roles_directory }}/{{ oc_product.short_name }}/oc_file/{{ operator_name }}.tar.gz"
  register: oc_file

- name: Make sure operator collection file exist
  ansible.builtin.fail:
    msg: "Operator collection file '/{{ operator_name }}.tar.gz' not found!"
  when: not oc_file.stat.exists
