#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
# Include ansible variables for product sub-operator being undeployed
- name: Include Java vars
  ansible.builtin.include_vars:
    file: "{{ zoscb_e2e_roles_directory }}/java/vars/main.yml"
  when: not java_vars_loaded

- name: Set java_vars_loaded flag
  ansible.builtin.set_fact:
    java_vars_loaded: true
  when: not java_vars_loaded

# Include sub operator role
- name: "Include role: 'java'"
  ansible.builtin.include_role:
    name: "java"

# Undeploy Java SUB-OPERATOR CUSTOM RESOURCES
- name: Uninstall validateJava instance
  ansible.builtin.include_tasks: "{{ java_cr_task_dir }}/uninstall/validateJava.yml"
  when:
    - hostvars[current_zosendpoint]._is_active
    - seaa_deploy_validate_crs | bool
    - sub_operator_java_create_validate_cr | bool
  with_items:
    - "{{ groups['zosendpoints'] }}"
  loop_control:
    loop_var: current_zosendpoint

- name: Uninstall javaInstance
  ansible.builtin.include_tasks: "{{ java_cr_task_dir }}/uninstall/javaInstance.yml"
  when:
    - hostvars[current_zosendpoint]._is_active
    - seaa_deploy_software_instances | bool
  with_items:
    - "{{ groups['zosendpoints'] }}"
  loop_control:
    loop_var: current_zosendpoint

- name: Undeploy Operator Collection and SubOperator
  when:
    - not zpm_consolidated_operator | bool
  block:

    # DELETE SUB-OPERATOR CONFIG
    - name: Destroy subOperatorConfig yaml
      ansible.builtin.include_tasks: "{{ zoscb_e2e_task_directory }}/operator_collection/destroy/subOperatorConfig.yml"
      when:
        - seaa_automation_strategy == "generate_deploy_yaml" or seaa_automation_strategy == "generate_yaml" or seaa_automation_strategy == "deploy_yaml"
        - seaa_deploy_role == "admin"
        - seaa_deploy_suboperator | bool

    # IMPORT OPERATOR COLLECTION
    - name: Destroy operatorCollection
      ansible.builtin.include_tasks: "{{ zoscb_e2e_task_directory }}/operator_collection/destroy/operatorCollection.yml"
      when:
        - seaa_deploy_role == "admin"
        - seaa_deploy_operator_collections | bool
