---
# Include ansible variables for product sub-operator being undeployed
- name: Include Oelcpp vars
  ansible.builtin.include_vars:
    file: "{{ zoscb_e2e_roles_directory }}/oelcpp/vars/main.yml"
  when: not oelcpp_vars_loaded

- name: Set oelcpp_vars_loaded flag
  ansible.builtin.set_fact:
    oelcpp_vars_loaded: true
  when: not oelcpp_vars_loaded

# Include sub operator role
- name: "Include role: 'oelcpp'"
  ansible.builtin.include_role:
    name: "oelcpp"

# Undeploy OelCpp SUB-OPERATOR CUSTOM RESOURCES
- name: Uninstall validateGo instance
  ansible.builtin.include_tasks: "{{ oelcpp_cr_task_dir }}/uninstall/validateOelcpp.yml"
  when:
    - hostvars[current_zosendpoint]._is_active
    - seaa_deploy_validate_crs | bool
    - sub_operator_oelcpp_create_validate_cr | bool
  with_items:
    - "{{ groups['zosendpoints'] }}"
  loop_control:
    loop_var: current_zosendpoint

- name: Uninstall goInstance
  ansible.builtin.include_tasks: "{{ oelcpp_cr_task_dir }}/uninstall/oelcppInstance.yml"
  when:
    - hostvars[current_zosendpoint]._is_active
    - seaa_deploy_software_instances | bool
  with_items:
    - "{{ groups['zosendpoints'] }}"
  loop_control:
    loop_var: current_zosendpoint


- name: Undeploy Operator Collection and SubOperator
  when:
    - not zpm_consolidated_operator | bool
  block:

    # DELETE SUB-OPERATOR CONFIG
    - name: Destroy subOperatorConfig yaml
      ansible.builtin.include_tasks: "{{ zoscb_e2e_task_directory }}/operator_collection/destroy/subOperatorConfig.yml"
      when:
        - seaa_automation_strategy == "generate_deploy_yaml" or seaa_automation_strategy == "generate_yaml" or seaa_automation_strategy == "deploy_yaml"
        - seaa_deploy_role == "admin"
        - seaa_deploy_suboperator | bool

    # IMPORT OPERATOR COLLECTION
    - name: Destroy operatorCollection
      ansible.builtin.include_tasks: "{{ zoscb_e2e_task_directory }}/operator_collection/destroy/operatorCollection.yml"
      when:
        - seaa_deploy_role == "admin"
        - seaa_deploy_operator_collections | bool
